export const UKRAINE_CITIES = [
  'Kyiv',
  'Kharkiv',
  'Odesa',
  'Dnipro',
  'Lviv',
  'Zaporizhzhia',
  'Kryvyi Rih',
  'Mykolaiv',
  'Vinnytsia',
  'Kherson',
  'Poltava',
  'Chernihiv',
  'Cherkasy',
  'Zhytomyr',
  'Sumy',
  'Rivne',
  'Ivano-Frankivsk',
  'Ternopil',
  'Lutsk',
  'Uzhhorod',
  'Kropyvnytskyi',
  'Chernivtsi',
  'Bila Tserkva',
  'Kramatorsk',
  'Kremenchuk',
  'Melitopol',
  'Mariupol',
  'Brovary',
  'Boryspil',
  'Mukachevo',
  'Drohobych',
  'Yalta',
] as const;
